name: Python CI
on:
  push:
    branches: [main]
  
jobs:
  build:
    name: BUILD
    strategy:
      matrix:
        python-version: [3.9.x, 3.10.x]
        platform: [ubuntu-latest]
    
    runs-on: ${{matrix.platform}}
    steps:
      - name: set up python ${{matrix.node-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: checkout code
        uses: actions/checkout@v2
      
      - name:
        run: python setup.py develop | python tests/test_money.py -v
        shell: bash